// Regroupement logique des mots de chaque chapitre : titre de sous-catégorie · 标题, puis les mots dans l'ordre d'apprentissage.
const GROUPS={
salut:[["Dire bonjour · 打招呼",["Bonjour","Bonsoir","Salut","Bonjour, Mademoiselle"]],["Faire connaissance · 初次见面",["Enchanté"]],
 ["Prendre des nouvelles · 问候近况",["Comment ça va ?","Comment vas-tu ?","Comment allez-vous ?","Ça va bien","Très bien, merci, et vous ?","Pas mal, merci","Comme ci, comme ça","Ça va mal"]],
 ["Politesse · 礼貌用语",["Merci","De rien","S'il vous plaît","Pardon"]],["Oui ou non · 是与否",["Oui","Non"]],["Dire au revoir · 道别",["Au revoir","À bientôt","À demain","Bonne nuit"]]],
presente:[["Mon nom · 我的名字",["Je m'appelle","Comment vous appelez-vous ?","le nom","le prénom"]],["Qui je suis · 我是谁",["Je suis","Tu es","étudiant","professeur","ami"]],
 ["D'où je viens · 我来自哪里",["D'où viens-tu ?","Je viens de Chine","Quelle est ta nationalité ?","Je suis chinois(e)","la France","la Chine","français","chinois","J'habite"]],
 ["Mon âge · 我的年龄",["l'âge","Quel âge as-tu ?","J'ai vingt-cinq ans"]]],
nombres:[["De 0 à 5 · 0到5",["zéro","un","deux","trois","quatre","cinq"]],["De 6 à 10 · 6到10",["six","sept","huit","neuf","dix"]]],
n11:[["De 11 à 16 · 11到16",["onze","douze","treize","quatorze","quinze","seize"]],["De 17 à 20 · 17到20",["dix-sept","dix-huit","dix-neuf","vingt"]]],
age:[["De 21 à 25 · 21到25",["vingt et un","vingt-deux","vingt-trois","vingt-quatre","vingt-cinq"]],["De 26 à 30 · 26到30",["vingt-six","vingt-sept","vingt-huit","vingt-neuf","trente"]],
 ["Demander et dire son âge · 问年龄和说年龄",["Quel âge as-tu ?","Quel âge avez-vous ?","J'ai vingt ans","J'ai vingt-cinq ans","l'âge","un an"]],["L'anniversaire · 生日",["l'anniversaire","Bon anniversaire !"]]],
questions:[["Les mots interrogatifs · 疑问词",["Est-ce que… ?","qui","que / quoi","quel / quelle","où","quand","comment","combien","pourquoi"]],["Des exemples · 例句",["Quel jour est-on ?","Que fais-tu ?","Où est-ce que tu habites ?"]]],
famille:[["Les parents · 父母",["le père","la mère"]],["Frères et sœurs · 兄弟姐妹",["le frère","la sœur"]],["Les enfants · 子女",["le fils","la fille","l'enfant"]],["Le couple · 夫妻",["le mari","la femme"]],["Les grands-parents · 祖父母",["le grand-père","la grand-mère"]],["Tous ensemble · 全家",["la famille"]]],
possessifs:[["Mon, ma, mes · 我的",["mon frère","ma sœur","mes amis"]],["Ton, ta, tes · 你的",["ton père","ta mère","tes enfants"]],["Son, sa, ses · 他/她的",["son livre","sa voiture","ses clés"]],
 ["Notre, nos · 我们的",["notre maison","nos amis"]],["Votre, vos · 您的",["votre ordinateur","vos chaussures"]],["Leur, leurs · 他们的",["leur chat","leurs enfants"]]],
animaux:[["À la maison · 家里的动物",["le chien","le chat","le lapin","le poisson"]],["À la ferme · 农场",["le cochon","le mouton","la poule","le canard","la vache","le cheval"]],["Sauvages et du monde · 野生动物",["l'éléphant","la girafe","le lion","le panda","la grenouille","le crabe"]]],
jours:[["En semaine · 工作日",["lundi","mardi","mercredi","jeudi","vendredi"]],["Le week-end · 周末",["samedi","dimanche","le week-end"]],["La semaine · 一周",["la semaine"]],
 ["Parler des jours · 谈论日子",["le lundi","Quel jour sommes-nous ?","Hier, c'était dimanche","Aujourd'hui, c'est lundi","Demain, c'est mardi"]]],
n40:[["De 30 à 34 · 30到34",["trente","trente et un","trente-deux","trente-trois","trente-quatre"]],["De 35 à 40 · 35到40",["trente-cinq","trente-six","trente-sept","trente-huit","trente-neuf","quarante"]],["Dans une date · 在日期中",["Le trente et un décembre"]]],
mois:[["Janvier à mars · 一月到三月",["janvier","février","mars"]],["Avril à juin · 四月到六月",["avril","mai","juin"]],["Juillet à septembre · 七月到九月",["juillet","août","septembre"]],["Octobre à décembre · 十月到十二月",["octobre","novembre","décembre"]],
 ["Le calendrier · 日历",["le mois","l'année","la date","Quelle est la date ?","C'est le cinq octobre","le premier janvier"]]],
n100:[["Les dizaines · 整十",["quarante","cinquante","soixante","soixante-dix","quatre-vingts","quatre-vingt-dix","cent"]],["Les cas particuliers · 特殊情况",["cinquante-cinq","soixante et un","soixante et onze","soixante-quinze","quatre-vingt-un","quatre-vingt-quinze"]]],
heure:[["Demander l'heure · 问时间",["Quelle heure est-il ?","À quelle heure ?"]],["Dire l'heure · 说时间",["Il est une heure","Il est huit heures","Il est trois heures dix","et quart","et demie","moins le quart","Il est midi","Il est minuit","À huit heures"]],
 ["Les moments de la journée · 一天的时段",["le matin","l'après-midi","le soir","la nuit","la minute"]]],
nombres2:[["Les centaines · 百",["cent","deux cents","deux cent trois","trois cents"]],["Les milliers · 千与百万",["mille","deux mille","dix mille","un million"]],["Un prix · 价格",["Ça coûte cent euros"]]],
meteo:[["Au printemps · 春天",["le printemps","Il fait doux","Il pleut"]],["En été · 夏天",["l'été","Il fait chaud","Il fait beau","Il y a du soleil","Il y a de l'orage"]],
 ["En automne · 秋天",["l'automne","Il fait frais","Il y a du vent"]],["En hiver · 冬天",["l'hiver","Il fait froid","Il neige"]],
 ["Demander et mesurer · 询问与测量",["Quel temps fait-il ?","la température","vingt degrés","moins cinq degrés"]]],
temps:[["Hier, aujourd'hui, demain · 昨天今天明天",["hier","aujourd'hui","maintenant","demain"]],["Dans la journée · 一天中",["le jour","l'heure","tôt","tard"]],["La fréquence · 频率",["toujours","souvent","parfois","jamais"]]],
vetements:[["Le haut · 上衣",["un tee-shirt","une chemise","un pull","un manteau"]],["Le bas · 下装",["un pantalon","une jupe","une robe"]],["Les accessoires · 配饰",["un chapeau","un bonnet","une écharpe","des chaussettes","des chaussures"]],
 ["Décrire ce qu'on porte · 描述穿着",["Il porte quoi ?","Il porte un t-shirt rouge","neuf","d'occasion"]],["Au magasin · 在商店",["la taille","la pointure","Je vais essayer ce t-shirt","Avez-vous une taille plus grande ?"]]],
couleurs:[["Les couleurs · 颜色",["blanc","noir","gris","rouge","orange","jaune","vert","bleu","violet","rose","marron"]],["Parler des couleurs · 谈论颜色",["Quelle est la couleur ?","C'est bleu"]]],
physique:[["L'âge · 年龄",["jeune","vieux / vieille"]],["La taille · 身高",["grand(e)","moyen(ne)","petit(e)"]],["La silhouette · 体型",["gros(se)","mince"]],["La beauté · 外貌",["beau / belle","laid(e)"]],
 ["Les détails · 细节",["une moustache","une barbe","des lunettes"]],["Des phrases · 句子",["Il est grand","Elle a les yeux bleus"]]],
cheveux:[["Les cheveux · 头发",["les cheveux","longs","courts","lisses / raides","frisés","bouclés"]],["La couleur des cheveux · 发色",["noirs","bruns","blonds","roux","gris"]],["Les yeux · 眼睛",["les yeux","marron","bleus","verts"]]],
chambre:[["Le coin repos · 睡觉区",["la chambre","le lit","le coussin","le doudou","l'armoire","le miroir"]],["Le coin travail · 学习区",["le bureau","la chaise","l'ordinateur portable","l'étagère","le livre"]],
 ["La décoration · 装饰",["la lampe","la fenêtre","le tableau","le tapis"]],["Des phrases · 句子",["Il y a un lit","Où est la lampe ?"]]],
maison:[["Les pièces · 房间",["le salon","la salle à manger","la cuisine","la chambre","la salle de bains","les toilettes"]],["Dehors · 户外",["le jardin","le balcon"]],["Dans la maison · 屋内",["la porte","la fenêtre","l'escalier","la table","la chaise","le lit"]]],
manger:[["J'ai faim, j'ai soif · 饿了渴了",["J'ai faim","J'ai soif","Je mange","Je bois de l'eau","Bon appétit !"]],["Boire · 饮料",["l'eau","le lait","le café","le thé","le vin"]],["Manger · 食物",["le pain","le riz","la viande","le poisson","l'œuf","le fromage","le légume","la pomme","le gâteau"]]],
fruits:[["Les fruits · 水果",["la pomme","la poire","la banane","la fraise","la cerise","le citron"]],["Les légumes · 蔬菜",["la tomate","la carotte","la pomme de terre","le concombre","la courgette","le poivron","le chou","l'avocat","l'oignon","l'ail"]]],
viandes:[["Viandes et poissons · 肉和鱼",["le bœuf","le porc","le poulet","le jambon","le poisson"]],["Œufs et produits laitiers · 蛋与乳制品",["les œufs","le lait","le yaourt","le fromage","le beurre"]],["Les féculents · 主食",["le riz","les pâtes","les céréales"]],["Assaisonner et plats · 调味与菜肴",["le sucre","le sel","la soupe"]]],
cuisine:[["Les quantités · 数量",["une boîte de sardines","une bouteille de lait","un verre d'eau","un kilo de farine","un litre de lait","un paquet de biscuits","une part de pizza","beaucoup de sucre","un peu de pâtes"]],["Les verbes de la cuisine · 厨房动词",["laver","éplucher","couper","ajouter","mélanger","cuire"]]],
resto:[["À l'arrivée · 入座",["Vous avez une table pour deux ?","la carte","le serveur / la serveuse"]],["Le repas · 一餐",["l'entrée","le plat principal","le dessert","la boisson"]],["Commander · 点餐",["Je voudrais…","C'est épicé ?","Sans gluten / sans lactose"]],
 ["Sur la table · 餐桌上",["une assiette","un verre","une bouteille d'eau","une fourchette","un couteau","une cuillère"]],["Payer · 结账",["L'addition, s'il vous plaît"]]],
commerces:[["Pour manger · 食品店",["la boulangerie","la boucherie","la poissonnerie","la fromagerie","le marché","le supermarché"]],["Autres magasins · 其他商店",["la librairie","le fleuriste","le magasin de vêtements","le coiffeur"]],["Les services · 服务",["la poste","la banque","la pharmacie"]],["Sortir · 外出",["le restaurant","le bar"]],["Des phrases · 句子",["Je vais à la boulangerie","Je vais chez le boulanger"]]],
marche:[["Demander · 询问",["Je voudrais un kilo de…","un kilo","une livre","Un peu plus","Un peu moins"]],["Le prix · 价格",["Combien ça coûte ?","frais"]],["Payer · 付款",["C'est tout","Voilà","la monnaie","le panier"]]],
courses:[["Les magasins · 商店",["le marché","le supermarché","la boulangerie"]],["Acheter · 购买",["le caddie","le sac","la liste de courses","le vendeur / la vendeuse"]],["L'argent · 钱",["l'argent","un euro","cher","pas cher","payer","la carte bancaire"]]],
corps:[["La tête · 头部",["la tête","la gorge","le cou"]],["Le haut du corps · 上身",["l'épaule","le bras","le coude","la main","le doigt","le dos","le ventre"]],["Le bas du corps · 下身",["la hanche","la jambe","le genou","la cheville","le pied"]]],
docteur:[["Prendre rendez-vous · 预约",["un rendez-vous","Où avez-vous mal ?"]],["J'ai mal · 我疼",["J'ai mal à la tête","J'ai mal au ventre","J'ai une migraine"]],["Je suis malade · 我生病了",["J'ai la fièvre","Je vomis","Je tousse","J'ai un rhume","Je suis fatigué(e)"]],["Les accidents · 受伤",["Je me suis cassé la jambe","Je me suis coupé le doigt","Au secours !"]]],
medic:[["Les médicaments · 药品",["le médicament","le sirop","le paracétamol","la vitamine C"]],["Les métiers · 医疗职业",["le médecin","l'infirmier / l'infirmière","le dentiste","le pharmacien / la pharmacienne"]],["Les lieux · 地点",["chez le médecin","la pharmacie","l'hôpital","les urgences"]]],
sports:[["Les sports d'équipe · 团体运动",["le football","le basketball","le volley-ball"]],["Avec une raquette · 球拍运动",["le tennis","le ping-pong"]],["Les sports individuels · 个人运动",["la natation","nager","le vélo","la course","courir","le yoga","la musculation"]],["Des phrases · 句子",["faire du sport","Je fais du vélo"]]],
loisirs:[["Les loisirs · 爱好",["la musique","le cinéma","le livre","le téléphone","voyager"]],["Le sport · 运动",["le sport","le football","nager"]]],
ville:[["Dans la rue · 街上",["la rue","l'avenue","le feu","le panneau stop","le rond-point","le pont"]],["Pour se reposer · 休闲处",["le parc","le banc","la fontaine","les escaliers"]],["Les bâtiments · 建筑",["la mairie","l'église","le musée","la bibliothèque","la police","l'aéroport"]]],
directions:[["Demander son chemin · 问路",["Où est… ?","Comment aller à… ?","Je cherche le parc","Je suis perdu(e)"]],["La position · 方位",["à gauche","à droite","tout droit","devant","derrière","à côté de","en face de"]],["Les verbes · 动词",["aller","tourner","continuer","traverser","suivre"]],["La fréquence · 频率",["souvent","parfois","rarement","jamais"]]],
lieux:[["Mon quartier · 我的街区",["la maison","l'école","le magasin","le restaurant","la rue","la ville","l'hôpital"]],["Les transports · 交通",["la gare","le métro","le bus","le train","la voiture","l'avion"]]],
taxi:[["Sur la route · 陆路",["la voiture","la moto","le scooter","le vélo","le bus","le taxi","à pied"]],["Sur rails et sous terre · 轨道交通",["le train","le métro"]],["Dans les airs et sur l'eau · 空中与水上",["l'avion","l'hélicoptère","le bateau"]],["Des phrases · 句子",["Je prends le bus","Je vais à l'école en bus"]]],
vacances:[["Où partir ? · 去哪里",["la plage","la mer","la montagne","la campagne","la forêt","le lac","la rivière","la ville","le village"]],["Où dormir ? · 住在哪里",["l'hôtel","le camping","la tente","la location","la chambre d'hôtes","la ferme"]],
 ["Que faire ? · 做什么",["se baigner","bronzer","se promener","faire de la randonnée","faire du surf","visiter","prendre des photos"]],["Les verbes du voyage · 旅行动词",["partir","voyager","dormir","rester","préférer"]],["Des phrases · 句子",["Je vais partir","Je vais à la mer","Je préfère la plage"]]],
retour:[["Poser les questions · 提问",["Tu pars en vacances ?","Où es-tu allé(e) pendant les vacances ?","Qu'est-ce que tu as fait pendant les vacances ?","Comment es-tu allé(e) ?"]],
 ["Où et comment · 去哪里、怎么去",["Je suis parti(e) en vacances à…","Je vais en Bretagne","C'est au bord de la mer","J'y suis allé(e) en train","On prend la voiture"]],
 ["Ce que j'ai fait · 我做了什么",["Je me suis baigné(e)","J'ai bronzé","J'ai visité un village","J'ai fait une randonnée","J'ai pris des photos","J'ai fait du surf","J'ai fait du bateau","J'ai fait de la plongée","J'ai fait un pique-nique","Je me suis promené(e)","J'ai goûté la cuisine locale"]],["La nature · 自然",["la nature"]]],
aeroport:[["Avant le vol · 登机前",["le billet","le passeport","la valise","le numéro de vol","l'enregistrement"]],["À l'aéroport · 在机场",["le terminal","la douane","le contrôle des passeports","la porte d'embarquement"]],["Départ et arrivée · 出发与到达",["le départ","l'arrivée","la clé"]]],
classe2:[["Parler en classe · 课堂交流",["Répétez après moi","Pouvez-vous répéter ?","Plus lentement, s'il vous plaît","Je ne comprends pas","J'ai une question"]],["Traduire · 翻译",["Comment dit-on… en français ?","Pouvez-vous traduire cette phrase ?","Quelle est la traduction de… ?","Essayez de le dire en français"]],
 ["Le matériel · 学习用品",["Le livre","Le cahier","Le stylo","Le crayon","La gomme","La règle"]],["La classe · 教室",["La classe","Le tableau","L'exercice"]]],
verbes:[["Regarder, écouter, parler · 看、听、说",["Regardez / Regarde","Écoutez / Écoute","Parlez / Parle"]],["Écrire et colorier · 写和涂色",["Écrivez / Écris","Coloriez / Colorie","Soulignez / Souligne","Entourez / Entoure","Recopiez / Recopie"]],
 ["Manipuler · 动手操作",["Coupez / Coupe","Collez / Colle","Ouvrez / Ouvre","Prenez / Prends","Distribuez / Distribue"]],["Lire et répéter · 读和重复",["Lisez / Lis","Répétez / Répète"]],["Bouger en classe · 课堂动作",["Asseyez-vous / Assis-toi","Levez-vous / Lève-toi","Levez le doigt / Lève le doigt"]]],
verbes2:[["Communiquer · 交流",["parler","demander","répondre","appeler"]],["Apprendre · 学习",["écouter","regarder","lire","écrire","comprendre","apprendre","répéter"]],["Chercher et aider · 寻找与帮助",["chercher","trouver","aider","attendre"]],["Commencer et finir · 开始与结束",["commencer","finir","ouvrir","fermer"]],
 ["La vie de tous les jours · 日常生活",["travailler","habiter","manger","boire","acheter","dormir"]],["Se déplacer · 移动",["partir","arriver"]]],
etre:[["Être et avoir · 是与有",["être","avoir"]],["Aller, venir, faire · 去、来、做",["aller","venir","faire"]],["Vouloir, pouvoir, devoir, savoir · 想要、能、必须、知道",["vouloir","pouvoir","devoir","savoir"]],["Prendre, donner, dire… · 拿、给、说……",["prendre","donner","dire","voir","mettre","aimer"]]],
conj:[["Être · 是",["je suis","tu es","il est","nous sommes","vous êtes","ils sont"]],["Avoir · 有",["j'ai","tu as","il a","nous avons"]],["Aller · 去",["je vais","tu vas","nous allons"]],["D'autres verbes · 其他动词",["je fais","je peux","je veux","je parle","je mange"]]],
conj3:[["Aller · 去",["je vais","tu vas","il / elle va","nous allons","vous allez","ils / elles vont"]],["Faire · 做",["je fais","tu fais","il / elle fait","nous faisons","vous faites","ils / elles font"]],
 ["Prendre · 拿",["je prends","tu prends","il / elle prend","nous prenons","vous prenez","ils / elles prennent"]],["Vouloir · 想要",["je veux","tu veux","il / elle veut","nous voulons","vous voulez","ils / elles veulent"]],
 ["Pouvoir · 能够",["je peux","tu peux","il / elle peut","nous pouvons","vous pouvez","ils / elles peuvent"]],["Dire · 说",["je dis","tu dis","il / elle dit","nous disons","vous dites","ils / elles disent"]],["Savoir · 知道",["je sais","tu sais","il / elle sait","nous savons","vous savez","ils / elles savent"]]]
};


// Petites aides pédagogiques : TIPS[chapitre]["*"] = en haut de la fiche ; TIPS[chapitre][titre du groupe] = sous le titre du groupe.
// Chaque ligne est bilingue « français · 中文 » (affichée selon la langue du menu).
const TIPS={
nombres:{"De 0 à 5 · 0到5":["Liaison : deux enfants → [dø zɑ̃.fɑ̃], trois amis → [tʁwa za.mi]. · 连读：deux enfants 读作 [dø zɑ̃.fɑ̃]，trois amis 读作 [tʁwa za.mi]。"]},
n11:{"*":["11 à 16 : des mots à apprendre par cœur. · 11到16需要直接记住。","17, 18, 19 = dix + sept / huit / neuf. · 17、18、19 = dix + 7 / 8 / 9。"]},
age:{"De 21 à 25 · 21到25":["21 = vingt et un (avec « et », sans trait d'union). Ensuite : vingt-deux, vingt-trois… · 21写作 vingt et un（有 et，不加连字符）；之后是 vingt-deux、vingt-trois……"],
 "Demander et dire son âge · 问年龄和说年龄":["On ne dit pas « je suis 25 ans » : en français, on dit « j'ai 25 ans » (verbe avoir). · 法语不说“je suis 25 ans”，而说 j'ai 25 ans（用 avoir，“有”）。"]},
jours:{"Parler des jours · 谈论日子":["le lundi = tous les lundis (une habitude) ; lundi = ce lundi-là. · le lundi 指每个星期一（习惯）；lundi 指具体的某个星期一。"]},
mois:{"Le calendrier · 日历":["On dit « en janvier » ou « au mois de janvier ». · 说 en janvier 或 au mois de janvier。","La date : le 1er = « le premier » ; ensuite le deux, le trois… (nombres normaux). · 日期：1号说 le premier，其余用普通数字：le deux、le trois……"]},
n40:{"*":["De 21 à 69 : on dit la dizaine, puis l'unité : trente-deux = 30 + 2. · 21到69：先说十位再说个位：trente-deux = 30 + 2。","Avec 1 : « et un » → vingt et un, trente et un… (jusqu'à soixante et un). · 个位是1时用 et un：vingt et un、trente et un……（到 soixante et un）。"]},
n100:{"Les dizaines · 整十":["La logique de 70, 80, 90 : · 70、80、90的构成逻辑：","70 = 60 + 10 → soixante-dix · 70 等于 60 + 10","80 = 4 × 20 → quatre-vingts · 80 等于 4 × 20","90 = 4 × 20 + 10 → quatre-vingt-dix · 90 等于 4 × 20 + 10"],
 "Les cas particuliers · 特殊情况":["71 = 60 + 11 (soixante et onze) ; 75 = 60 + 15 ; 95 = 4 × 20 + 15. · 71 = 60 + 11；75 = 60 + 15；95 = 4 × 20 + 15。","81 = 4 × 20 + 1 → quatre-vingt-un (sans « et »). · 81 写作 quatre-vingt-un（不加 et）。"]},
nombres2:{"Les centaines · 百":["cent prend un « s » seulement s'il n'y a rien après : deux cents, mais deux cent trois. · cent 后面没有其他数字时才加 s：deux cents；但 deux cent trois 不加。"],
 "Les milliers · 千与百万":["mille ne change jamais : deux mille, dix mille. · mille 永远不变：deux mille、dix mille。"]},
heure:{"Dire l'heure · 说时间":["Il est une heure (singulier) ; deux heures (pluriel). Midi et minuit : sans « heure ». · une heure 用单数；deux heures 用复数。midi、minuit 后不加 heure。"]},
meteo:{"*":["Il fait + adjectif : il fait chaud, froid, doux, frais, beau (comme « il fait chaud » = it makes hot). Le « il » est impersonnel. · il fait + 形容词：il fait chaud / froid / doux / frais / beau。il 是虚指主语，没有实际含义。",
 "Il y a + nom : il y a du vent, du soleil, de l'orage, des nuages. · il y a + 名词：il y a du vent / du soleil / de l'orage / des nuages（有风、有太阳……）。",
 "Pluie et neige : on utilise un verbe → il pleut, il neige. · 雨和雪用动词：il pleut、il neige。"],
 "Au printemps · 春天":["Saisons : au printemps, mais en été, en automne, en hiver. · 季节介词：au printemps，其余用 en été / en automne / en hiver。"]},
couleurs:{"Les couleurs · 颜色":["Les couleurs s'accordent : une robe verte, des pantalons bleus. Mais orange et marron ne changent pas. · 颜色形容词与名词配合：une robe verte、des pantalons bleus；但 orange、marron 不变。"]},
possessifs:{"*":["mon / ma / mes s'accordent avec le nom qui suit, pas avec le propriétaire : « sa voiture » = la voiture de lui ou d'elle. · mon / ma / mes 与后面的名词配合，而不是与拥有者配合：sa voiture 可以是他的车，也可以是她的车。"]},
docteur:{"J'ai mal · 我疼":["J'ai mal à + partie du corps : au (le) ventre, à la tête, à l'épaule, aux dents. · J'ai mal à + 身体部位：au ventre、à la tête、à l'épaule、aux dents。"]},
directions:{"La position · 方位":["à côté de / en face de + nom : à côté de la gare. · à côté de / en face de + 名词：à côté de la gare。"]},
vetements:{"Le haut · 上衣":["un / une / des : un pull, une chemise, des chaussures (le nom pluriel prend « des »). · un / une / des：un pull、une chemise、des chaussures。"]},
etre:{"*":["Ces verbes sont irréguliers : il faut les apprendre par cœur. · 这些是不规则动词，需要熟记。"]}
};
(function(){for(const id of Object.keys(GROUPS)){const c=CATS.find(x=>x.id===id);if(!c)continue;const by=new Map(c.items.map(i=>[i[0],i])),out=[];
  GROUPS[id].forEach(([t,keys])=>keys.forEach(k=>{const it=by.get(k);if(it){it[5]=t;out.push(it);by.delete(k)}}));
  by.forEach(it=>{it[5]="Autres · 其他";out.push(it)});c.items=out}})();
